exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("table_name")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("table_name").insert([
        { hour: "00", minutes: "00" },
        { hour: "00", minutes: "15" },
        { hour: "00", minutes: "30" },
        { hour: "00", minutes: "45" },
        { hour: "01", minutes: "00" },
        { hour: "01", minutes: "15" },
        { hour: "01", minutes: "30" },
        { hour: "01", minutes: "45" },
        { hour: "02", minutes: "00" },
        { hour: "02", minutes: "15" },
        { hour: "02", minutes: "30" },
        { hour: "02", minutes: "45" },
        { hour: "03", minutes: "00" },
        { hour: "03", minutes: "15" },
        { hour: "03", minutes: "30" },
        { hour: "03", minutes: "45" },
        { hour: "04", minutes: "00" },
        { hour: "04", minutes: "15" },
        { hour: "04", minutes: "30" },
        { hour: "04", minutes: "45" },
        { hour: "05", minutes: "00" },
        { hour: "05", minutes: "15" },
        { hour: "05", minutes: "30" },
        { hour: "05", minutes: "45" },
        { hour: "06", minutes: "00" },
        { hour: "06", minutes: "15" },
        { hour: "06", minutes: "30" },
        { hour: "06", minutes: "45" },
        { hour: "07", minutes: "00" },
        { hour: "07", minutes: "15" },
        { hour: "07", minutes: "30" },
        { hour: "07", minutes: "45" },
        { hour: "08", minutes: "00" },
        { hour: "08", minutes: "15" },
        { hour: "08", minutes: "30" },
        { hour: "08", minutes: "45" },
        { hour: "09", minutes: "00" },
        { hour: "09", minutes: "15" },
        { hour: "09", minutes: "30" },
        { hour: "09", minutes: "45" },
        { hour: "10", minutes: "00" },
        { hour: "10", minutes: "15" },
        { hour: "10", minutes: "30" },
        { hour: "10", minutes: "45" },
        { hour: "11", minutes: "00" },
        { hour: "11", minutes: "15" },
        { hour: "11", minutes: "30" },
        { hour: "11", minutes: "45" },
        { hour: "12", minutes: "00" },
        { hour: "12", minutes: "15" },
        { hour: "12", minutes: "30" },
        { hour: "12", minutes: "45" },
        { hour: "13", minutes: "00" },
        { hour: "13", minutes: "15" },
        { hour: "13", minutes: "30" },
        { hour: "13", minutes: "45" },
        { hour: "14", minutes: "00" },
        { hour: "14", minutes: "15" },
        { hour: "14", minutes: "30" },
        { hour: "14", minutes: "45" },
        { hour: "15", minutes: "00" },
        { hour: "15", minutes: "15" },
        { hour: "15", minutes: "30" },
        { hour: "15", minutes: "45" },
        { hour: "16", minutes: "00" },
        { hour: "16", minutes: "15" },
        { hour: "16", minutes: "30" },
        { hour: "16", minutes: "45" },
        { hour: "17", minutes: "00" },
        { hour: "17", minutes: "15" },
        { hour: "17", minutes: "30" },
        { hour: "17", minutes: "45" },
        { hour: "18", minutes: "00" },
        { hour: "18", minutes: "15" },
        { hour: "18", minutes: "30" },
        { hour: "18", minutes: "45" },
        { hour: "19", minutes: "00" },
        { hour: "19", minutes: "15" },
        { hour: "19", minutes: "30" },
        { hour: "19", minutes: "45" },
        { hour: "20", minutes: "00" },
        { hour: "20", minutes: "15" },
        { hour: "20", minutes: "30" },
        { hour: "20", minutes: "45" },
        { hour: "21", minutes: "00" },
        { hour: "21", minutes: "15" },
        { hour: "21", minutes: "30" },
        { hour: "21", minutes: "45" },
        { hour: "22", minutes: "00" },
        { hour: "22", minutes: "15" },
        { hour: "22", minutes: "30" },
        { hour: "22", minutes: "45" },
        { hour: "23", minutes: "00" },
        { hour: "23", minutes: "15" },
        { hour: "23", minutes: "30" },
        { hour: "23", minutes: "45" },
      ]);
    });
};
